// web/user/src/components/CaptchaWidget.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import type { CaptchaPayload, GuestConfig } from '../api/comm'

const props=defineProps<{config:GuestConfig|null}>()
const containerId='captcha-'+Math.random().toString(36).slice(2)
const ready=ref(false)
let widgetId:number|string|null=null
let renderedKey:string|null=null

function key(){
  const c=props.config
  if(!c?.is_captcha)return null
  const type=c.captcha_type||'recaptcha'
  if(type==='turnstile'&&c.turnstile_site_key)return 'turnstile:'+c.turnstile_site_key
  if(type==='recaptcha'&&c.recaptcha_site_key)return 'recaptcha:'+c.recaptcha_site_key
  if(type==='recaptcha-v3'&&c.recaptcha_v3_site_key)return 'recaptcha-v3:'+c.recaptcha_v3_site_key
  return null
}

function loadScript(src:string,id:string){
  return new Promise<void>((resolve,reject)=>{
    if(document.getElementById(id)){resolve();return}
    const script=document.createElement('script')
    script.id=id
    script.src=src
    script.async=true
    script.defer=true
    script.onload=()=>resolve()
    script.onerror=()=>reject(new Error('Failed to load captcha script'))
    document.head.appendChild(script)
  })
}

async function mountWidget(){
  const current=key()
  if(current&&current===renderedKey)return
  ready.value=false
  if(!props.config?.is_captcha||!current){renderedKey=null;return}
  renderedKey=current
  const type=props.config.captcha_type||'recaptcha'
  try{
    if(type==='turnstile'&&props.config.turnstile_site_key){
      await loadScript('https://challenges.cloudflare.com/turnstile/v0/api.js','tx-cf-turnstile')
      const turnstile=(window as unknown as {turnstile?:{render:(selector:string,opts:Record<string,unknown>)=>string}}).turnstile
      if(turnstile){
        widgetId=turnstile.render('#'+containerId,{sitekey:props.config.turnstile_site_key,theme:'auto'})
        ready.value=true
      }
      return
    }
    if(type==='recaptcha'&&props.config.recaptcha_site_key){
      await loadScript('https://www.google.com/recaptcha/api.js?render=explicit','tx-google-recaptcha')
      const grecaptcha=(window as unknown as {grecaptcha?:{render:(id:string,opts:Record<string,unknown>)=>number}}).grecaptcha
      if(grecaptcha){
        widgetId=grecaptcha.render(containerId,{sitekey:props.config.recaptcha_site_key})
        ready.value=true
      }
      return
    }
    if(type==='recaptcha-v3'&&props.config.recaptcha_v3_site_key){
      await loadScript('https://www.google.com/recaptcha/api.js?render='+encodeURIComponent(props.config.recaptcha_v3_site_key),'tx-google-recaptcha-v3')
      const grecaptcha=(window as unknown as {grecaptcha?:{ready:(cb:()=>void)=>void}}).grecaptcha
      if(grecaptcha){
        await new Promise<void>(resolve=>grecaptcha.ready(resolve))
        ready.value=true
      }
    }
  }catch{
    renderedKey=null
  }
}

async function getPayload():Promise<CaptchaPayload>{
  if(!props.config?.is_captcha)return {}
  const type=props.config.captcha_type||'recaptcha'
  if(type==='turnstile'){
    const turnstile=(window as unknown as {turnstile?:{getResponse:(id?:string)=>string}}).turnstile
    return {turnstile_token:turnstile?.getResponse(widgetId as string)||undefined}
  }
  if(type==='recaptcha'){
    const grecaptcha=(window as unknown as {grecaptcha?:{getResponse:(id?:number)=>string}}).grecaptcha
    return {recaptcha_data:grecaptcha?.getResponse(widgetId as number)||undefined}
  }
  if(type==='recaptcha-v3'&&props.config.recaptcha_v3_site_key){
    const grecaptcha=(window as unknown as {grecaptcha?:{execute:(key:string,opts:{action:string})=>Promise<string>}}).grecaptcha
    if(!ready.value||!grecaptcha)return {skip_recaptcha_v3:true}
    try{
      const token=await grecaptcha.execute(props.config.recaptcha_v3_site_key,{action:'submit'})
      return token?{recaptcha_v3_token:token}:{skip_recaptcha_v3:true}
    }catch{
      return {skip_recaptcha_v3_error:true}
    }
  }
  return {}
}

function reset(){
  const type=props.config?.captcha_type||'recaptcha'
  if(type==='turnstile'){
    const turnstile=(window as unknown as {turnstile?:{reset:(id?:string)=>void}}).turnstile
    turnstile?.reset(widgetId as string)
  }else if(type==='recaptcha'){
    const grecaptcha=(window as unknown as {grecaptcha?:{reset:(id?:number)=>void}}).grecaptcha
    grecaptcha?.reset(widgetId as number)
  }
}

onMounted(()=>void mountWidget())
watch(()=>props.config,()=>void mountWidget())
onBeforeUnmount(()=>{widgetId=null;renderedKey=null})
defineExpose({getPayload,reset})
</script>

<template>
  <div v-if="config?.is_captcha" class="captcha-wrap"><div :id="containerId"/></div>
</template>

// web/admin/src/components/CaptchaWidget.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react'
import type { CaptchaPayload, GuestConfig } from '../api/comm'

const TURNSTILE_SRC = 'https://challenges.cloudflare.com/turnstile/v0/api.js'
const RECAPTCHA_SRC = 'https://www.google.com/recaptcha/api.js'

type TurnstileApi = {
  render: (target: string, options: Record<string, unknown>) => string
  getResponse: (id?: string) => string
  reset: (id?: string) => void
}

type ReCaptchaApi = {
  render: (target: string, options: Record<string, unknown>) => number
  getResponse: (id?: number) => string
  reset: (id?: number) => void
  ready: (callback: () => void) => void
  execute: (siteKey: string, options: { action: string }) => Promise<string>
}

type CaptchaWindow = Window & { turnstile?: TurnstileApi; grecaptcha?: ReCaptchaApi }

function captchaWindow() {
  return window as CaptchaWindow
}

function loadScript(src: string, id: string) {
  return new Promise<void>((resolve, reject) => {
    if (document.getElementById(id)) {
      resolve()
      return
    }
    const script = document.createElement('script')
    script.id = id
    script.src = src
    script.async = true
    script.defer = true
    script.onload = () => resolve()
    script.onerror = () => reject(new Error('Failed to load captcha script'))
    document.head.appendChild(script)
  })
}

function captchaType(config: GuestConfig | null) {
  return config?.captcha_type || 'recaptcha'
}

export function captchaSiteKey(config: GuestConfig | null) {
  if (!config || Number(config.is_captcha || 0) !== 1) return ''
  const type = captchaType(config)
  if (type === 'turnstile') return String(config.turnstile_site_key || '')
  if (type === 'recaptcha-v3') return String(config.recaptcha_v3_site_key || '')
  return String(config.recaptcha_site_key || '')
}

export type CaptchaWidgetHandle = {
  getPayload: () => Promise<CaptchaPayload>
  reset: () => void
}

export const CaptchaWidget = forwardRef<CaptchaWidgetHandle, { config: GuestConfig | null }>(
  function CaptchaWidget({ config }, ref) {
    const [containerId] = useState(() => 'admin-captcha-' + Math.random().toString(36).slice(2))
    const widgetId = useRef<number | string | null>(null)
    const [ready, setReady] = useState(false)
    const type = captchaType(config)
    const siteKey = captchaSiteKey(config)
    const active = Boolean(siteKey)

    useEffect(() => {
      widgetId.current = null
      setReady(false)
      if (!siteKey) return
      let cancelled = false
      const mount = async () => {
        try {
          if (type === 'turnstile') {
            await loadScript(TURNSTILE_SRC, 'admin-cf-turnstile')
            if (cancelled) return
            const api = captchaWindow().turnstile
            if (!api) return
            widgetId.current = api.render('#' + containerId, { sitekey: siteKey, theme: 'auto' })
            setReady(true)
            return
          }
          if (type === 'recaptcha-v3') {
            await loadScript(
              RECAPTCHA_SRC + '?render=' + encodeURIComponent(siteKey),
              'admin-google-recaptcha-v3',
            )
            if (cancelled) return
            const api = captchaWindow().grecaptcha
            if (!api) return
            await new Promise<void>(resolve => api.ready(() => resolve()))
            if (cancelled) return
            setReady(true)
            return
          }
          await loadScript(RECAPTCHA_SRC + '?render=explicit', 'admin-google-recaptcha')
          if (cancelled) return
          const api = captchaWindow().grecaptcha
          if (!api) return
          widgetId.current = api.render(containerId, { sitekey: siteKey })
          setReady(true)
        } catch {
          if (!cancelled) setReady(false)
        }
      }
      void mount()
      return () => {
        cancelled = true
      }
    }, [type, siteKey, containerId])

    useImperativeHandle(
      ref,
      () => ({
        getPayload: async () => {
          if (!active) return {}
          if (type === 'turnstile') {
            const token = captchaWindow().turnstile?.getResponse(widgetId.current as string)
            return token ? { turnstile_token: token } : {}
          }
          if (type === 'recaptcha') {
            const token = captchaWindow().grecaptcha?.getResponse(widgetId.current as number)
            return token ? { recaptcha_data: token } : {}
          }
          if (type === 'recaptcha-v3' && ready) {
            try {
              const token = await captchaWindow().grecaptcha?.execute(siteKey, { action: 'login' })
              return token ? { recaptcha_v3_token: token } : {}
            } catch {
              return {}
            }
          }
          return {}
        },
        reset: () => {
          if (type === 'turnstile') captchaWindow().turnstile?.reset(widgetId.current as string)
          else if (type === 'recaptcha') captchaWindow().grecaptcha?.reset(widgetId.current as number)
        },
      }),
      [active, ready, siteKey, type],
    )

    if (!active) return null
    return (
      <div className="admin-captcha">
        <div id={containerId} />
      </div>
    )
  },
)
